micronaut:
    security: #mincronaut basic auth
        enabled: true
        endpoints:
            login:
                enabled: true
            logout:
                enabled: true
            oauth: #micronaut security jwt
                enabled: true
        token:
            basicAuth:
                enabled: false
            jwt:
                enabled: true
                bearer:
                    enabled: false #[1]mematikan authentication bearer
                cookie:
                    enabled: true #[1]menghidupkan penyimpanan jwt di cookie
                signatures:         #[1] kesimpulan -> saat menggunakan Cookie, Auth Bearer tidak bisa digunakan dan sebaliknya, jika bearer mau digunakan, cookie harus dimatikan!!!
                    secret:
                        generator:
                            secret: "TmFtZTpCb2JieXxOaWNrIE5hbWU6QWt5b25nfEUtbWFpbDpib2JieUB0b2tvZGlzdHJpYnV0b3IuY29tfE1vYmlsZSBQaG9uZSBOdW1iZXI6KzYyODEyOTMzMDgwMjB8RmFjZWJvb2s6L2t5b25neHxUd2l0dGVyOkByeW9reW9uZ3xsYXQ6LTYuMTMyNTMzM3xsb25nOjEwNi43NjgxODAxLDE3eg=="
                            base64: true
                            jws-algorithm: HS256
        session: #micronaut security session
            enabled: true
            login-success-target-url: /
            login-failure-target-url: /login/authFailed
    application:
        name: test-authentication
    http:
        client:
            logger-name: testauth

datasources:
    default:
        url: jdbc:mysql://localhost:3306/test_authentication?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
        driverClassName: "com.mysql.jdbc.Driver"

#tag::jpa[] //untuk cek di folder test.app.domain jika ada setiap perubahan maka ada pembaruan table di database.
jpa:
    default:
        packages-to-scan:
            - 'test.authentication.domain.security' # <1>
            - 'test.authentication.domain.app.cif' # <2>

        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                hbm2ddl:
                    auto: update
                show_sql: true
#end::jpa[]

#tag::application[]
application:
    max: 10
#end::application[]

#tag::kafka[]
---
kafka:
    bootstrap:
        servers: localhost:9092
#end:kafka[]